// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: blogs.sql

package database

import (
	"context"
)

const createBlog = `-- name: CreateBlog :one

INSERT INTO blogs(title, summary, content,status, published_at,slug)
VALUES(
    $1,
    $2,
    $3,
    $4,
    CASE WHEN $4='published' THEN NOW() ELSE NULL END,
    $5
)
RETURNING blog_id, title, summary, content, created_at, updated_at, status, published_at, slug
`

type CreateBlogParams struct {
	Title   string
	Summary string
	Content string
	Status  string
	Slug    string
}

func (q *Queries) CreateBlog(ctx context.Context, arg CreateBlogParams) (Blog, error) {
	row := q.db.QueryRowContext(ctx, createBlog,
		arg.Title,
		arg.Summary,
		arg.Content,
		arg.Status,
		arg.Slug,
	)
	var i Blog
	err := row.Scan(
		&i.BlogID,
		&i.Title,
		&i.Summary,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.PublishedAt,
		&i.Slug,
	)
	return i, err
}
