// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: change_blog_status.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateBlogStatus = `-- name: UpdateBlogStatus :exec
UPDATE blogs
SET status = $2, published_at = CASE WHEN $2='published' THEN NOW() ELSE NULL END
WHERE blog_id = $1
`

type UpdateBlogStatusParams struct {
	BlogID uuid.UUID
	Status string
}

func (q *Queries) UpdateBlogStatus(ctx context.Context, arg UpdateBlogStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateBlogStatus, arg.BlogID, arg.Status)
	return err
}
