// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: change_post_status.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updatePostStatus = `-- name: UpdatePostStatus :exec
UPDATE posts
SET status = $2, published_at = CASE WHEN $2='publish' THEN NOW() ELSE NULL END
WHERE posts_id = $1
`

type UpdatePostStatusParams struct {
	PostsID uuid.UUID
	Status  string
}

func (q *Queries) UpdatePostStatus(ctx context.Context, arg UpdatePostStatusParams) error {
	_, err := q.db.ExecContext(ctx, updatePostStatus, arg.PostsID, arg.Status)
	return err
}
