// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: delete_blog_by_id.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteBlogById = `-- name: DeleteBlogById :exec

DELETE FROM blogs
WHERE blog_id = $1
`

func (q *Queries) DeleteBlogById(ctx context.Context, blogID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBlogById, blogID)
	return err
}
