// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: delete_post_by_id.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deletePostById = `-- name: DeletePostById :exec

DELETE FROM posts
WHERE posts_id = $1
`

func (q *Queries) DeletePostById(ctx context.Context, postsID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePostById, postsID)
	return err
}
