// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_post_by_slug.sql

package database

import (
	"context"
)

const getPostBySlug = `-- name: GetPostBySlug :one
SELECT posts_id, title, summary, post, created_at, updated_at, status, published_at, slug
FROM posts
WHERE slug=$1
`

func (q *Queries) GetPostBySlug(ctx context.Context, slug string) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPostBySlug, slug)
	var i Post
	err := row.Scan(
		&i.PostsID,
		&i.Title,
		&i.Summary,
		&i.Post,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.PublishedAt,
		&i.Slug,
	)
	return i, err
}
