// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_blog_by_slug.sql

package database

import (
	"context"
)

const getBlogBySlug = `-- name: GetBlogBySlug :one
SELECT blog_id, title, summary, content, created_at, updated_at, status, published_at, slug
FROM blogs
WHERE slug=$1
`

func (q *Queries) GetBlogBySlug(ctx context.Context, slug string) (Blog, error) {
	row := q.db.QueryRowContext(ctx, getBlogBySlug, slug)
	var i Blog
	err := row.Scan(
		&i.BlogID,
		&i.Title,
		&i.Summary,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.PublishedAt,
		&i.Slug,
	)
	return i, err
}
