// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_blogs_dashboard.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getBlogsDashboard = `-- name: GetBlogsDashboard :many

SELECT blog_id, title, summary, status
FROM blogs
`

type GetBlogsDashboardRow struct {
	BlogID  uuid.UUID
	Title   string
	Summary string
	Status  string
}

func (q *Queries) GetBlogsDashboard(ctx context.Context) ([]GetBlogsDashboardRow, error) {
	rows, err := q.db.QueryContext(ctx, getBlogsDashboard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBlogsDashboardRow
	for rows.Next() {
		var i GetBlogsDashboardRow
		if err := rows.Scan(
			&i.BlogID,
			&i.Title,
			&i.Summary,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
