// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_posts_dashboard.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getPostsDashboard = `-- name: GetPostsDashboard :many

SELECT posts_id, title, summary, status
FROM posts
`

type GetPostsDashboardRow struct {
	PostsID uuid.UUID
	Title   string
	Summary string
	Status  string
}

func (q *Queries) GetPostsDashboard(ctx context.Context) ([]GetPostsDashboardRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostsDashboard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostsDashboardRow
	for rows.Next() {
		var i GetPostsDashboardRow
		if err := rows.Scan(
			&i.PostsID,
			&i.Title,
			&i.Summary,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
