// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_posts.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getPosts = `-- name: GetPosts :many

SELECT posts_id, title, summary, published_at, slug
FROM posts
WHERE status='publish'
`

type GetPostsRow struct {
	PostsID     uuid.UUID
	Title       string
	Summary     string
	PublishedAt sql.NullTime
	Slug        string
}

func (q *Queries) GetPosts(ctx context.Context) ([]GetPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostsRow
	for rows.Next() {
		var i GetPostsRow
		if err := rows.Scan(
			&i.PostsID,
			&i.Title,
			&i.Summary,
			&i.PublishedAt,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
