// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_blog_by_id.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getBlogByID = `-- name: GetBlogByID :one

SELECT blog_id, title, summary, content, created_at, updated_at, status, published_at, slug 
FROM blogs
WHERE blog_id=$1
`

func (q *Queries) GetBlogByID(ctx context.Context, blogID uuid.UUID) (Blog, error) {
	row := q.db.QueryRowContext(ctx, getBlogByID, blogID)
	var i Blog
	err := row.Scan(
		&i.BlogID,
		&i.Title,
		&i.Summary,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.PublishedAt,
		&i.Slug,
	)
	return i, err
}
