// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_post_by_id.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getPostByID = `-- name: GetPostByID :one

SELECT posts_id, title, summary, post, created_at, updated_at, status, published_at, slug 
FROM posts
WHERE posts_id=$1
`

func (q *Queries) GetPostByID(ctx context.Context, postsID uuid.UUID) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPostByID, postsID)
	var i Post
	err := row.Scan(
		&i.PostsID,
		&i.Title,
		&i.Summary,
		&i.Post,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.PublishedAt,
		&i.Slug,
	)
	return i, err
}
