// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type Blog struct {
	BlogID      uuid.UUID
	Title       string
	Summary     string
	Content     string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	Status      string
	PublishedAt sql.NullTime
	Slug        string
}
