// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type Post struct {
	PostsID     uuid.UUID
	Title       string
	Summary     string
	Post        string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	Status      sql.NullString
	PublishedAt sql.NullTime
}
