// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: posts.sql

package database

import (
	"context"
	"database/sql"
)

const createPost = `-- name: CreatePost :one

INSERT INTO posts(title, summary, post,status, published_at)
VALUES(
    $1,
    $2,
    $3,
    $4,
    CASE WHEN status='published' THEN NOW() ELSE NULL END
)
RETURNING posts_id, title, summary, post, created_at, updated_at, status, published_at
`

type CreatePostParams struct {
	Title   string
	Summary string
	Post    string
	Status  sql.NullString
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.Title,
		arg.Summary,
		arg.Post,
		arg.Status,
	)
	var i Post
	err := row.Scan(
		&i.PostsID,
		&i.Title,
		&i.Summary,
		&i.Post,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.PublishedAt,
	)
	return i, err
}
