// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: update_post.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updatePost = `-- name: UpdatePost :exec
UPDATE posts
SET 
title=$2, 
summary=$3, 
post=$4, 
status=$5,
published_at = CASE WHEN $5='publish' AND published_at IS NULL THEN NOW() ELSE published_at END
WHERE posts_id=$1
`

type UpdatePostParams struct {
	PostsID uuid.UUID
	Title   string
	Summary string
	Post    string
	Status  string
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) error {
	_, err := q.db.ExecContext(ctx, updatePost,
		arg.PostsID,
		arg.Title,
		arg.Summary,
		arg.Post,
		arg.Status,
	)
	return err
}
