// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: update_blog.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateBlog = `-- name: UpdateBlog :exec
UPDATE blogs
SET 
title=$2, 
summary=$3, 
content=$4, 
status=$5,
published_at = CASE WHEN $5='published' AND published_at IS NULL THEN NOW() ELSE published_at END
WHERE blog_id=$1
`

type UpdateBlogParams struct {
	BlogID  uuid.UUID
	Title   string
	Summary string
	Content string
	Status  string
}

func (q *Queries) UpdateBlog(ctx context.Context, arg UpdateBlogParams) error {
	_, err := q.db.ExecContext(ctx, updateBlog,
		arg.BlogID,
		arg.Title,
		arg.Summary,
		arg.Content,
		arg.Status,
	)
	return err
}
